#!/bin/bash

# Provisioning script for Centos 6 on SoftLayer
# Get to a known spot
cd ~

# Come up to date
yum update

# Get our metadata
curl https://api.service.softlayer.com/rest/v3/SoftLayer_Resource_Metadata/getUserMetadata > /tmp/SetupMetadata

# Install CloudFuse (allows us to mount object storage)

#  install pre-reqs
 yum -y install gcc libcurl libcurl-devel fuse fuse-devel fuse-libs libxml2 libxml2-devel
 
 #  get the code
wget -O -   https://github.com/redbo/cloudfuse/tarball/master | tar xvz

# install
cd redbo-cloudfuse-*
./configure
make
make install
cd ~

# Make a directory to mount our first object storage volume
mkdir ObjectStorage

# Not quite done yet - need credentials for the volume
# Go to the softlayer portal, storage tab, object storage selection
# select the object storage name (maybe there is only one), select the location (Dallas 5 or other)
# and click "View Credentials"
# create a file .cloudfuse and in it:

# username=[the Username line]
# api_key=[API Key line]
# authurl=[one of the Authentication endpoint lines]

 
